Feat/friend page
hugh-burgess/CapstoneNF2021 pull request #14
Opened 2021-04-28 16:29 UTC by hugh-burgess

resolves #13

2021-04-28 22:11 UTC, FriederikeM requested changes
LGTM, but there is a lot of commented code that you want to get rid of before you merge

2021-04-28 22:11 UTC, FriederikeM commented on client/src/components/friends-page/AddButton.js
> +    // formData.append("file", selectedFile);
Commented code? no thanks!

2021-04-28 22:11 UTC, FriederikeM commented on client/src/components/friends-page/AddButton.js
> +      // file: selectedFile,
no no

2021-04-28 22:11 UTC, FriederikeM commented on client/src/components/friends-page/AddButton.js
> +  // };
Don't merge them comments

2021-04-28 22:11 UTC, FriederikeM commented on client/src/components/friends-page/AddButton.js
> +    console.log(isClicked);
you can delete the console log

2021-04-28 22:11 UTC, FriederikeM commented on client/src/components/friends-page/AddButton.js
> +            /> */}
more

2021-04-29 07:07 UTC, soerendolling approved these changes
Looks good to me

2021-04-29 08:03 UTC, merged