Animations
hugh-burgess/CapstoneNF2021 pull request #83
Opened 2021-05-25 17:39 UTC by hugh-burgess

Animations! Chucked in a few where applicable or otherwise where they ccould work... Enjoy!

2021-05-25 19:17 UTC, Shari-alt reviewed
Nice! Love these animations! :) Works out really good!

2021-05-26 09:31 UTC, marwinburesch requested changes
Good work, mate! You could just replace all animations with framer motion, or write all the animations yourself :D 
🐜 
gg wp

2021-05-26 09:31 UTC, marwinburesch commented on client/src/components/animations/SlideInTransition.js
> +export default function SlideInTransition() {
I think the name is not correct since this is not a general animation. It's a specific component because it always uses `useFriends`.
Can't you use the `children` prop 
https://reactjs.org/docs/composition-vs-inheritance.html

2021-05-26 09:31 UTC, marwinburesch commented on client/src/components/friends-page/FriendsContent.js
> +      <div>
This redundant I think

2021-05-26 09:31 UTC, marwinburesch commented on client/src/components/register/RegisterForm.js
> +        </Link>
Seems like refactoring of your `RegisterForm`

2021-05-26 09:31 UTC, marwinburesch commented on client/src/components/search-page/Search.js
> +        <SlideUpTransition filter={filter} />
I think is this a weird change, I would've expected something like this:
```suggestion
        <SlideUpTransition>
             <Dogs filter={filter} />
        </ SlideUpTransition>
```
OR add the transition to `Dogs`

2021-05-26 09:31 UTC, marwinburesch commented on client/src/components/animations/InitialTransition.js
> +  };
Why did you call it `blackBox`?

2021-05-26 10:03 UTC, merged